class ASCII:
    start: str = " A "
    end: str = "Z"
    ball: str = "⧭"
    pole: str = "+"
    pole_empty: str = " "
    wall_h: str = "---"
    wall_h_empty: str = "   "
    wall_v: str = "|"
    wall_v_empty: str = " "
    cell: str = "   "
    cell_visited: str = " ⋅ "
    cell_path_floodfill: str = " f "
    cell_path_dijkstra: str = " j "
    cell_path_astar: str = " a "
    cell_path_bfs: str = " b "
    cell_path_dfs: str = " d "
    cell_path_general: str = " # "